name: "Add LICENSE file to Go Repositories"

on:
  workflow_dispatch: {}
concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  build-provider-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - id: set-matrix
        run: |
          provider=$(jq -rcM "{ provider: keys }" provider.json)
          echo "matrix=$provider" >> $GITHUB_OUTPUT

  add-license-file:
    needs: build-provider-matrix
    name: "Add LICENSE File"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{fromJSON(needs.build-provider-matrix.outputs.matrix)}}
      max-parallel: 10
    steps:
      - name: Generate GitHub App token
        id: app-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ secrets.GH_APP_ID }}
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}
          owner: cdktn-io
          repositories: cdktn-io/cdktn-provider-${{ matrix.provider }}-go

      - name: Get GitHub App User ID
        id: get-user-id
        run: echo "user-id=$(gh api "/users/${{ steps.app-token.outputs.app-slug }}[bot]" --jq .id)" >> "$GITHUB_OUTPUT"
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}

      - name: Checkout this repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          path: main

      - name: Checkout cdktn-provider-${{ matrix.provider }}-go Repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          repository: cdktn-io/cdktn-provider-${{ matrix.provider }}-go
          token: ${{ steps.app-token.outputs.token }}
          fetch-depth: 0
          path: provider

      - name: Setup Copywrite
        uses: hashicorp/setup-copywrite@32638da2d4e81d56a0764aa1547882fc4d209636 # v1.1.3

      - name: Set git identity
        run: |-
          git config user.name "${{ steps.app-token.outputs.app-slug }}[bot]"
          git config user.email "${{ steps.get-user-id.outputs.user-id }}+${{ steps.app-token.outputs.app-slug }}[bot]@users.noreply.github.com>"
        working-directory: ./provider

      - name: Delete old branches from previous runs
        run: |
          git branch -r | egrep -o "add-update-license-file.*" | xargs -n 1 git push origin --delete
        working-directory: ./provider
        continue-on-error: true

      - name: Add Mozilla Public License
        run: copywrite license --spdx "MPL-2.0"
        working-directory: ./provider
        env:
          GH_REPO: cdktn-io/cdktn-provider-${{ matrix.provider }}-go
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}

      - name: Check for changes
        id: git_diff
        run: |
          if (( $(git status -s | wc -l) > 0 )); then echo "has_changes=true" >> $GITHUB_OUTPUT; fi
        working-directory: ./provider

      - if: steps.git_diff.outputs.has_changes
        name: Sleep for 2 seconds to avoid rate limits
        run: sleep 2s

      - if: steps.git_diff.outputs.has_changes
        name: Commit license file and push changes
        run: |
          git checkout -b add-update-license-file-${{ github.run_number }}-${{ github.run_attempt }}
          git add .
          git commit -m "Add / Update LICENSE file"
          git push --set-upstream origin add-update-license-file-${{ github.run_number }}-${{ github.run_attempt }}
        working-directory: ./provider

      - if: steps.git_diff.outputs.has_changes
        name: "Create PR"
        uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
        with:
          github-token: ${{ steps.app-token.outputs.token }}
          retries: 5
          retry-exempt-status-codes: 400,401,404
          script: |
            const {resolve} = require('path')
            const scriptPath = resolve("./main/.github/lib/create-pr")
            const script = require(scriptPath)
            await script({
              github,
              branchName: "add-update-license-file-${{ github.run_number }}-${{ github.run_attempt }}",
              prTitle: "Add / Update LICENSE file",
              fullRepoName: "cdktn-provider-${{matrix.provider}}-go",
              mergePullRequest: true
            })
