name: "Delete stale branches in provider repos"
on:
  workflow_dispatch: {}
concurrency: ${{ github.workflow }}-${{ github.ref }}
jobs:
  build-provider-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - id: set-matrix
        run: |
          provider=$(jq -rcM "{ provider: keys }" provider.json)
          echo "matrix=$provider" >> $GITHUB_OUTPUT
  cleanup-branches:
    needs: build-provider-matrix
    name: "Clean up branches"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{fromJSON(needs.build-provider-matrix.outputs.matrix)}}
      max-parallel: 10
    steps:
      - name: Generate GitHub App token
        id: app-token
        uses: actions/create-github-app-token@29824e69f54612133e76f7eaac726eef6c875baf  # v2.2.1
        with:
          app-id: ${{ secrets.GH_APP_ID }}
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}
          owner: cdktn-io
          repositories: cdktn-provider-${{ matrix.provider }}
      - name: Get GitHub App User ID
        id: get-user-id
        run: echo "user-id=$(gh api "/users/${{ steps.app-token.outputs.app-slug }}[bot]" --jq .id)" >> "$GITHUB_OUTPUT"
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
      - name: Checkout cdktn-provider-${{ matrix.provider }} Repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          repository: cdktn-io/cdktn-provider-${{ matrix.provider }}
          token: ${{ steps.app-token.outputs.token }}
          fetch-depth: 0
      - name: Set git identity
        run: |-
          git config user.name "${{ steps.app-token.outputs.app-slug }}[bot]"
          git config user.email "${{ steps.get-user-id.outputs.user-id }}+${{ steps.app-token.outputs.app-slug }}[bot]@users.noreply.github.com"
      - name: Delete old branches from previous repo-manager runs
        run: git branch -r | egrep -o "upgrade-provider-project.*" | xargs -n 1 git push origin --delete
        continue-on-error: true # don't fail the run if these branches never existed
      - name: Delete old branches from when we used to build providers against cdktf@next
        run: git branch -r | egrep -o "cdktf-next-pr.*" | xargs -n 1 git push origin --delete
        continue-on-error: true # don't fail the run if these branches never existed
      - name: Delete old temporary branches from previous repo-manager runs
        run: git branch -r | egrep -o "foo-bar.*" | xargs -n 1 git push origin --delete
        continue-on-error: true # don't fail the run if these branches never existed
      - name: Delete old renovate branches that were never used
        run: git branch -r | egrep -o ".*renovate.*" | xargs -n 1 git push origin --delete
        continue-on-error: true # don't fail the run if these branches never existed
      - name: Delete old update-main branch that has not been used in 3 years
        run: git branch -r | egrep -o "update-main" | xargs -n 1 git push origin --delete
        continue-on-error: true # don't fail the run if these branches never existed
      - name: Delete old Projen branch name convention that has not been used in 3 years # the one we use nowadays is github-actions/upgrade-main
        run: git branch -r | egrep -o "github-actions/upgrade" | xargs -n 1 git push origin --delete
        continue-on-error: true # don't fail the run if these branches never existed
      - name: Delete another Projen branch name convention that has not been used in 3 years
        run: git branch -r | egrep -o "github-actions/upgrade-dependencies" | xargs -n 1 git push origin --delete
        continue-on-error: true # don't fail the run if these branches never existed
